import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
    sidebar: [
    { type: "html", value: "<div style='text-align:center;color:var(--ifm-menu-color);font-size:.9rem'>CherryGrove</div>" },
        "cg/overview",
        "cg/roadmap",
        "cg/developing",
        {
            type: "category",
            label: "Releasing",
            link: {
                type: "doc",
                id: "cg/releasing"
            },
            items: [{
                type: "autogenerated",
                dirName: "cg/releasing"
            }]
        },
        {
            type: "category",
            label: "Design",
            link: {
                type: "doc",
                id: "cg/design"
            },
            items: [{
                type: "autogenerated",
                dirName: "cg/design"
            }]
        },
        {
            type: "category",
            label: "References",
            link: {
                type: "doc",
                id: "cg/references"
            },
            items: [{
                type: "autogenerated",
                dirName: "cg/references"
            }]
        },
        "cg/contributing",
        "cg/faq",
    { type: "html", value: "<div style='margin:.5rem .6rem;border-top:solid 1px var(--ifm-toc-border-color)'/><div style='text-align:center;color:var(--ifm-menu-color);padding-top:.1rem;font-size:.9rem'>Content Pack</div>" },
        "pack/overview",
        {
            type: "category",
            label: "Getting Started",
            link: {
                type: "doc",
                id: "pack/getting-started"
            },
            items: [{
                type: "autogenerated",
                dirName: "pack/languages"
            }]
        },
        "pack/toolchain",
        {
            type: "category",
            label: "References",
            link: {
                type: "doc",
                id: "pack/umi"
            },
            items: [{
                type: "autogenerated",
                dirName: "pack/umi"
            }]
        },
    { type: "html", value: "<div style='margin:.5rem .6rem;border-top:solid 1px var(--ifm-toc-border-color)'/><div style='text-align:center;color:var(--ifm-menu-color);padding-top:.1rem;font-size:.9rem'>Vanilla</div>" },
        "vanilla/overview",
        {
            type: "category",
            label: "Tutorial",
            link: {
                type: "doc",
                id: "vanilla/tutorial"
            },
            items: [{
                type: "autogenerated",
                dirName: "vanilla/tutorial"
            }]
        },
        "vanilla/design",
        {
            type: "category",
            label: "Wiki",
            link: {
                type: "doc",
                id: "vanilla/wiki"
            },
            items: [{
                type: "autogenerated",
                dirName: "vanilla/wiki"
            }]
        },
        "vanilla/contributing",
    ]
} satisfies SidebarsConfig;